### ISSUE TITLE
Can't delete company

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#41]
**Description**:

**Steps to reproduce**:
1. Create a company and order for user
2. Send a request to delete this company

**Expected result**:
Step 2: Company is successfully deleted

**Actual result**:
Step 2: Exception occurs.
`org.postgresql.util.PSQLException: ERROR: update or delete on table &quot;couriers&quot; violates foreign key constraint &quot;fkh9cn2kgltuune91r2hiysdg03&quot; on table &quot;orders&quot;
  Detail: Key (user_id)=(1) is still referenced from table &quot;orders&quot;.
	org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)...`

**Root-cause analysis**:
Looks like query to delete company tries to delete a user. This should be fixed.

**Fix performed**:

**Comment by lenyuk1999oo** [comment]
Company is successfully deleted.
