### ISSUE TITLE
DOC - Purpose, scope and product perspective

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#44]
- [x] Create the following parts of needful documentation:
  1. Purpose
  2. Scope
  3. Product perspective

Example link https://belitsoft.com/blog/software-requirements-specification-document-example-international-standard

**Comment by YuraPunchyk** [comment]
[Документація1-3.docx](https://github.com/MikeMalyar/PrimumPartusApp/files/3674787/1-3.docx)
