### ISSUE TITLE
DOC - Product functions, user characteristics and limitation

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#45]
- [x] Create the following parts of needful documentation:
  4. Product functions
  5. User characteristics
  6. Limitations

Example link https://belitsoft.com/blog/software-requirements-specification-document-example-international-standard

**Comment by YuraPunchyk** [comment]
[Документація4-6.docx](https://github.com/MikeMalyar/PrimumPartusApp/files/3703860/4-6.docx)
