### ISSUE TITLE
DOC - Apportioning of requirements, specific requirements and external interfaces

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#46]
- [x] Create the following parts of needful documentation:
  8. Apportioning of requirements
  9. Specific requirements
  10. External interfaces

Example link https://belitsoft.com/blog/software-requirements-specification-document-example-international-standard

**Comment by lenyuk1999oo** [comment]
[Documentation8-9.docx](https://github.com/MikeMalyar/PrimumPartusApp/files/3674681/Documentation8-9.docx)

**Comment by lenyuk1999oo** [comment]
[Documentation8-9.docx](https://github.com/MikeMalyar/PrimumPartusApp/files/3700881/Documentation8-9.docx)
