### ISSUE TITLE
DOC - Assumptions and dependencies, and functions

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#47]
- [x] Create the following parts of needful documentation:
  7. Assumptions and dependencies
  11. Functions

Example link https://belitsoft.com/blog/software-requirements-specification-document-example-international-standard

**Comment by ViktorPelepiak** [comment]
[Документація.docx](https://github.com/MikeMalyar/PrimumPartusApp/files/3674768/default.docx)

**Comment by ozhga1999** [comment]
[7 Assumptions and dependencies.docx](https://github.com/MikeMalyar/PrimumPartusApp/files/3838309/7.Assumptions.and.dependencies.docx)
