### ISSUE TITLE
DOC - Usability and performance requirements

### ISSUE THREAD

**Issue by MikeMalyar** [MikeMalyar/PrimumPartusApp#48]
- [x] Create the following parts of needful documentation:
  12. Usability requirements
  13. Performance requirements

Example link https://belitsoft.com/blog/software-requirements-specification-document-example-international-standard

**Comment by ozhga1999** [comment]
[Док12.docx](https://github.com/MikeMalyar/PrimumPartusApp/files/3926026/12.docx)
